version: '3'
services:
  dev-db:
    image: postgres:14
    container_name: dev-db-container
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: webrtc
    labels:
      - 'name=postgres'
      - 'mode=standalone'
